80 cli remove spot spot from commands
inductiva/inductiva pull request #1025
Opened 2024-01-31 17:08 UTC by Pbarbosa92

No more --spot spot

2024-01-31 17:11 UTC, IvanPombo approved these changes
Confirm the behavior and let me know before merging.

2024-02-01 09:11 UTC, Pbarbosa92 commented
Working as expected!
<img width="857" alt="Captura de ecrã 2024-02-01, às 09 11 36" src="https://github.com/inductiva/inductiva/assets/157368229/e11ab374-eb9e-45fb-aebc-75040a5a0743">

2024-02-01 09:39 UTC, IvanPombo approved these changes
While we are at it, please address the decimal places for the cost and add a `n` parameter for the number of machines. See my comment below.

Else...

# QA Approved

2024-02-01 09:39 UTC, IvanPombo commented on inductiva/_cli/cmd_resources/cost.py
As you are it here: Can you round here the cost result to three decimal places and moreover add the `-n` parameter to compute the cost for `n` number of machines.

2024-02-01 10:29 UTC, sergiomsantos requested changes

2024-02-01 10:29 UTC, sergiomsantos commented on inductiva/resources/machine_groups.py
> +    return round(float(estimated_cost), 3)
this is not the right place to round the values. They should be returned as is and only round when printing.

2024-02-01 10:29 UTC, sergiomsantos commented on inductiva/_cli/cmd_resources/cost.py
> +        print(f"Estimated cost of machine: {cost} $/h.")
```suggestion
        print(f"Estimated cost of machine: {cost:.3f} $/h.")
```

2024-02-01 10:29 UTC, sergiomsantos commented on inductiva/_cli/cmd_resources/cost.py
> +              f": {cost*num_machines} ({cost}) $/h.")
```suggestion
              f": {cost*num_machines} ({cost:.3f}) $/h.")
```

2024-02-01 12:40 UTC, merged