Expand machine types
inductiva/inductiva pull request #1053
Opened 2024-02-05 15:16 UTC by IvanPombo

TLDR: Extend machine types available for the API to incorporate all possibilities. Note: This is still hard coded, because the endpoint to retrieve it is not yet available.

## Description

Expand the available machine types and possible variants that are available on Google Cloud. The list function was expanded to include machines with different memory types and local ssd.

2024-02-05 15:38 UTC, Pbarbosa92 approved these changes

2024-02-05 15:44 UTC, hpenedones commented on inductiva/resources/machine_types.py
> -    for machine_type in AVAILABLE_MACHINES.keys():
Thanks Ivan!

2024-02-05 16:03 UTC, AugustoPeres approved these changes
LGTM! Left just minor comments

2024-02-05 16:06 UTC, IvanPombo commented on inductiva/resources/machine_types.py
> +            for memory in extra_configs[0]:
Notice that they are exactly the same. The problem is that some machine types have only two memories with more vcpus.

2024-02-05 16:08 UTC, IvanPombo commented on inductiva/resources/machine_types.py
> +        memory_list = configs.get("memory", ["highmem", "standard", "highcpu"])
Not sure, because it actually sets a default value as we wish.

2024-02-05 23:48 UTC, sergiomsantos requested changes
the implementation (namely the dict schema) is a bit difficult to understand.
I would rather have this information in a more explicit json file with a clearer schema:

#### Example:
```json
{
    "c2": {
        "standard": {
            "vcpus": [2, 4, 8, 16, 32, 60],
            "description": "Intel A1 1st generation with X GB of memory per vCPU."
        }
    },
    "c3": {
        "standard": {
            "vcpus": [4, 8, 22, 44, 88, 176],
            "description": "Intel A2 2nd generation with Y GB of memory per vCPU."
        },
        "standard-ssd": {
            "vcpus": [4, 8, 22, 44, 88, 176],
            "description": "Intel A2 2nd generation with Y GB of memory per vCPU and local SSD storage."
        },
        ...
```

We can make it a bit less verbose by using yaml (`pip install pyyaml`):

```yaml
c2:
  standard:
    vcpus: [2, 4, 8, 16, 32, 60]
    description: Intel A1 1st generation with X GB of memory per vCPU.
c3:
  standard:
    vcpus: [4, 8, 22, 44, 88, 176]
    description: Intel A2 2nd generation with Y GB of memory per vCPU.
  standard-ssd:
    vcpus: [4, 8, 22, 44, 88, 176]
    description: Intel A2 2nd generation with Y GB of memory per vCPU and local SSD storage.
```

2024-02-05 23:48 UTC, sergiomsantos commented on inductiva/resources/machine_types.py
> +    },
this is what I get when I run the code in this file for the `c3` machines:

```
c3-highmem-4
c3-highmem-8
c3-highmem-22
c3-highmem-44
c3-highmem-88
c3-highmem-176
c3-standard-4
c3-standard-8
c3-standard-22
c3-standard-44
c3-standard-88
c3-standard-176
c3-highcpu-4
c3-highcpu-8
c3-highcpu-22
c3-highcpu-44
c3-highcpu-88
c3-highcpu-176
c3-standard-8-lssd
c3-standard-22-lssd
c3-standard-44-lssd
c3-standard-88-lssd
c3-standard-176-lssd
```

Is this correct? I would suppose that `lssd` would apply to all 🤔 !

2024-02-08 17:39 UTC, IvanPombo commented
@sarmento @sergiomsantos This is now how users will see the machine types via CLI. WDYT?

```bash
$ inductiva resources available

Machine types provided in Google Cloud

c2: Intel Xeon Cascade Lake (2nd Gen) processor.
  > c2-standard: [2, 4, 8, 16, 32, 60]

c3: Intel Xeon Sapphire Rapids (4th Gen) processor.
  > c3-highcpu: [4, 8, 22, 44, 88, 176]
  > c3-standard: [4, 8, 22, 44, 88, 176]
  > c3-highmem: [4, 8, 22, 44, 88, 176]

h3: (Available Soon) Intel Xeon Sapphire Rapids (4th Gen) processor.
Simultaneous multithreading disabled, i.e., vCPU represents an entire core.
  > h3-standard: [88]

c2d: AMD EPYC Milan (3rd Gen) processor.
  > c2d-highcpu: [2, 4, 8, 16, 32, 56, 112]
  > c2d-standard: [2, 4, 8, 16, 32, 56, 112]
  > c2d-highmem: [2, 4, 8, 16, 32, 56, 112]

c3d: AMD EPYC Genoa (4th Gen) processor.
  > c3d-highcpu: [4, 8, 16, 30, 60, 90, 180, 360]
  > c3d-standard: [4, 8, 16, 30, 60, 90, 180, 360]
  > c3d-highmem: [4, 8, 16, 30, 60, 90, 180, 360]

e2: Intel Xeon (up to Skylake, 1st Gen) and AMD EPYC (up to Milan, 3rd Gen) processors.
Automatically selected based on availability.
  > e2-highcpu: [2, 4, 8, 16, 32]
  > e2-standard: [2, 4, 8, 16, 32]
  > e2-highmem: [2, 4, 8, 16]

n2: Intel Xeon Ice Lake and Cascade Lake processors (3rd and 2nd Gen).
Cascade Lake default up to 80 vCPUs and Ice Lake for larger machines.
  > n2-highcpu: [2, 4, 8, 16, 32, 48, 64, 80, 96]
  > n2-standard: [2, 4, 8, 16, 32, 48, 64, 80, 96, 128]
  > n2-highmem: [2, 4, 8, 16, 32, 48, 64, 80, 96, 128]

n2d: AMD EPYC Milan or ROME processors (3rd and 2nd Gen).
  > n2d-highcpu: [2, 4, 8, 16, 32, 48, 64, 80, 96, 128, 224]
  > n2d-standard: [2, 4, 8, 16, 32, 48, 64, 80, 96, 128, 224]
  > n2d-highmem: [2, 4, 8, 16, 32, 48, 64, 80, 96]

n1: Intel Xeon (up to Skylake, 1st Gen) processor.
Automatically selected based on availability.
  > n1-highcpu: [1, 2, 4, 8, 16, 32, 64, 96]
  > n1-standard: [1, 2, 4, 8, 16, 32, 64, 96]
  > n1-highmem: [1, 2, 4, 8, 16, 32, 64, 96]
```

2024-02-08 17:49 UTC, Pbarbosa92 commented on inductiva/_cli/cmd_resources/list.py
> +    for _, provider_resources in resources_available.items():
If we don't use the key why not?
```suggestion
    for provider_resources in resources_available.values():
```

2024-02-08 17:49 UTC, Pbarbosa92 commented on inductiva/_cli/cmd_resources/list.py
> +                _ = type_info["description"]
why this?

2024-02-08 17:49 UTC, Pbarbosa92 commented on inductiva/resources/machine_types.py
> +MACHINE_TYPES_FILE = os.path.join(os.path.dirname(__file__),
I would move this to constants.

2024-02-08 17:49 UTC, Pbarbosa92 commented on inductiva/resources/machine_types.py
> +    for _, provider_resources in resources_available.items():
```suggestion
    for provider_resources in resources_available.values():
```

2024-02-08 17:51 UTC, sarmento commented
> @sarmento @sergiomsantos This is now how users will see the machine types via CLI. WDYT? In the near term, we will add a way to fetch specific resources with higher verbosity.
> 
> ```shell
> $ inductiva resources available
> 
> Machine types provided in Google Cloud
> 
> c2: Intel Xeon Cascade Lake (2nd Gen) processor.
>   > c2-standard: [2, 4, 8, 16, 32, 60]
> 
> c3: Intel Xeon Sapphire Rapids (4th Gen) processor.
>   > c3-highcpu: [4, 8, 22, 44, 88, 176]
>   > c3-standard: [4, 8, 22, 44, 88, 176]
>   > c3-highmem: [4, 8, 22, 44, 88, 176]
> 
> h3: (Available Soon) Intel Xeon Sapphire Rapids (4th Gen) processor.
> Simultaneous multithreading disabled, i.e., vCPU represents an entire core.
>   > h3-standard: [88]
> 
> c2d: AMD EPYC Milan (3rd Gen) processor.
>   > c2d-highcpu: [2, 4, 8, 16, 32, 56, 112]
>   > c2d-standard: [2, 4, 8, 16, 32, 56, 112]
>   > c2d-highmem: [2, 4, 8, 16, 32, 56, 112]
> 
> c3d: AMD EPYC Genoa (4th Gen) processor.
>   > c3d-highcpu: [4, 8, 16, 30, 60, 90, 180, 360]
>   > c3d-standard: [4, 8, 16, 30, 60, 90, 180, 360]
>   > c3d-highmem: [4, 8, 16, 30, 60, 90, 180, 360]
> 
> e2: Intel Xeon (up to Skylake, 1st Gen) and AMD EPYC (up to Milan, 3rd Gen) processors.
> Automatically selected based on availability.
>   > e2-highcpu: [2, 4, 8, 16, 32]
>   > e2-standard: [2, 4, 8, 16, 32]
>   > e2-highmem: [2, 4, 8, 16]
> 
> n2: Intel Xeon Ice Lake and Cascade Lake processors (3rd and 2nd Gen).
> Cascade Lake default up to 80 vCPUs and Ice Lake for larger machines.
>   > n2-highcpu: [2, 4, 8, 16, 32, 48, 64, 80, 96]
>   > n2-standard: [2, 4, 8, 16, 32, 48, 64, 80, 96, 128]
>   > n2-highmem: [2, 4, 8, 16, 32, 48, 64, 80, 96, 128]
> 
> n2d: AMD EPYC Milan or ROME processors (3rd and 2nd Gen).
>   > n2d-highcpu: [2, 4, 8, 16, 32, 48, 64, 80, 96, 128, 224]
>   > n2d-standard: [2, 4, 8, 16, 32, 48, 64, 80, 96, 128, 224]
>   > n2d-highmem: [2, 4, 8, 16, 32, 48, 64, 80, 96]
> 
> n1: Intel Xeon (up to Skylake, 1st Gen) processor.
> Automatically selected based on availability.
>   > n1-highcpu: [1, 2, 4, 8, 16, 32, 64, 96]
>   > n1-standard: [1, 2, 4, 8, 16, 32, 64, 96]
>   > n1-highmem: [1, 2, 4, 8, 16, 32, 64, 96]
> ```

I love this. I think adding a description about each CPU type is really really helpful. I think users will learn a lot just by using the CLI and will be able to make more informed decisions.

@hpenedones wdyt? 
Would adding the year of release of each processor series also help?

2024-02-08 17:54 UTC, hpenedones commented
Love it too!

2024-02-08 17:55 UTC, IvanPombo commented
@sarmento @hpenedones 

I didn't want it to be to clutter, so the idea is that to fetch more specific information users can just do:
```bash
inductiva resources available --provider gcp --series c2

c2: Intel Xeon Cascade Lake (2nd Gen) processor.
  > c2-standard: [2, 4, 8, 16, 32, 60] - 4 GB of memory per vCPU
```

And we can add more information in this case.

2024-02-09 13:04 UTC, sergiomsantos approved these changes

2024-02-09 13:05 UTC, merged