Get machine by name
inductiva/inductiva pull request #1222
Opened 2024-03-21 10:58 UTC by AugustoPeres

This pull request adds a function that allows retrieval of a single machine group by its name:

```
>>> import inductiva
>>> mg = inductiva.resources.machine_groups.get_by_name("api-6j0zskh4hmcv1wjevnwe2o176")
>>> mg
MachineGroup(name="api-6j0zskh4hmcv1wjevnwe2o176")
```

2024-03-21 15:09 UTC, sergiomsantos requested changes
missing unit tests;
a single machine group can now be retrieved directly from the backend.

2024-03-21 15:09 UTC, sergiomsantos commented on inductiva/resources/machine_groups.py
> +    return None
there's already an endpoint for this: `/compute/group/{name}`
You should be able to get the machine directly.

2024-03-21 15:09 UTC, sergiomsantos commented on inductiva/resources/machine_groups.py
> +def _get_machine_group_class_from_api_response(mg: dict):
make it more explicit. It is easier for testing purposes and decouples it from having to have a dict.
What if the dict doesn't have the required kesy?

```suggestion
def _get_machine_group_class_from_api_response(type: str, is_elastic: bool):
    """Get the suitable machine group class for the given arguments""" 
```

2024-03-21 15:09 UTC, sergiomsantos commented on inductiva/resources/machine_groups.py
> +        mg_class = _get_machine_group_class_from_api_response(mg)
```suggestion
        mg_class = _get_machine_group_class_from_api_response(
                mg["type"], mg["is_elastic"])
```

2024-03-22 11:16 UTC, AugustoPeres commented
## QA

Launch every type of machine. Use the function (screen-shot above) to fetch the machine by name

2024-03-22 12:02 UTC, IvanPombo requested changes
LGTM! But I am curious how you have tested anything with it, since just by pulling the branch and starting the machine it doesn't work.

The quick fix, is to merge the PR on the ICE client, since I have done the corresponding changes there.

2024-03-22 12:04 UTC, AugustoPeres commented
> LGTM! But I am curious how you have tested anything with it, since just by pulling the branch and starting the machine it doesn't work.
> 
> The quick fix, is to merge the PR on the ICE client, since I have done the corresponding changes there.

It fails on launching the machine but not on fetching. I just launched the machines from a different virtual environment

2024-03-22 12:25 UTC, AugustoPeres commented
> LGTM! But I am curious how you have tested anything with it, since just by pulling the branch and starting the machine it doesn't work.
> 
> The quick fix, is to merge the PR on the ICE client, since I have done the corresponding changes there.

@ Ivan Pombo, changed base and merged with your branch

2024-03-22 17:25 UTC, AugustoPeres commented
*NOTE*: This pull request now also has changes from https://github.com/inductiva/inductiva/pull/1229 and https://github.com/inductiva/inductiva/pull/1218 which where necessary for testing.

They should disappear once those pull requests are merged to dev

2024-03-25 17:54 UTC, sergiomsantos approved these changes

2024-03-26 12:04 UTC, Pbarbosa92 commented
**QA**
✅ 
I created 3 machine groups and selected each one by name.
<img width="641" alt="Captura de ecrã 2024-03-26, às 12 04 06" src="https://github.com/inductiva/inductiva/assets/157368229/a510876f-d6c5-4a61-a0c7-d7334643ec85">

2024-03-26 12:48 UTC, IvanPombo approved these changes

2024-03-26 12:48 UTC, merged