adds the option to disable task logs
inductiva/inductiva pull request #1344
Opened 2024-04-23 09:38 UTC by AugustoPeres

2024-04-23 13:10 UTC, sergiomsantos requested changes

2024-04-23 13:10 UTC, sergiomsantos commented on inductiva/tasks/streams.py
> +
```suggestion
    def _disable_logs(self):
        client = api.get_client()
        payload = {"task_id": self.task_id}
        tasks_api.TasksApi(client).disable_task_logs(payload)

```

2024-04-23 16:22 UTC, Pbarbosa92 commented on inductiva/tasks/streams.py
> +            signal.signal(sig, self._handle_termination)
Why don't we just do 
```
if self._end_of_stream or self._keyboard_interrupt:
      self._disable_logs()
      break
```
I don't think there is a way to capture a sigkill.
@sergiomsantos can give a better input on this.

2024-04-30 09:25 UTC, sergiomsantos requested changes
let's keep the initial version. If needed, we can iterate afterwards.

2024-04-30 09:25 UTC, sergiomsantos commented on inductiva/tasks/streams.py
> +        sys.exit()
let's remove this method.

2024-04-30 09:25 UTC, sergiomsantos commented on inductiva/tasks/task.py
> +        self._api.disable_task_logs({"task_id": self.id})
not used.

2024-04-30 14:46 UTC, sergiomsantos approved these changes

2024-05-03 08:41 UTC, closed without merging