Add file commands
inductiva/inductiva pull request #1711
Opened 2024-11-21 15:02 UTC by rodrigotuna

This PR adds commands for interacting with files while the simulation is running.

Commands:
- `inductiva tasks ls <task_id>`
- `inductiva tasks tail <task_id> <filename>`

2024-12-02 09:53 UTC, Pbarbosa92 requested changes
After testing I've changed my mind.

We need to change some names. We already have `inductiva tasks list`it would make sense to me that `inductiva tasks ls` would do the same as the list.

Maybe this could be `inductiva tasks track list <id>`  and `inductiva tasks track tail <id> <filename>`. Not sure about this names but having list/ls in two places is confusing.

2024-12-02 10:55 UTC, rodrigotuna commented
> After testing I've changed my mind.
> 
> We need to change some names. We already have `inductiva tasks list`it would make sense to me that `inductiva tasks ls` would do the same as the list.
> 
> Maybe this could be `inductiva tasks track list <id>` and `inductiva tasks track tail <id> <filename>`. Not sure about this names but having list/ls in two places is confusing.

Would you agree with something like `inductiva tasks list_dir <id>`? Otherwise it would be too lengthy.

2024-12-02 14:05 UTC, Pbarbosa92 approved these changes

2024-12-03 17:30 UTC, rodrigotuna commented on inductiva/_cli/cmd_tasks/tail.py
> +    logging.getLogger().setLevel(level=logging.WARNING)
Aiortc is too verbose in level=INFO

2024-12-04 11:11 UTC, hpenedones commented on inductiva/tasks/file_tracker.py
> +    aiortc.RTCIceServer("stun:34.79.246.4:3478"),
I will now create a DNS entry for webtrc.inductiva.ai for this IP address...

2024-12-11 17:18 UTC, merged