Add number of lines parameter
inductiva/inductiva pull request #1764
Opened 2024-12-17 17:29 UTC by rodrigotuna

This PR adds the parameter to specify the desired number of output lines in the tail operation.

2024-12-18 09:12 UTC, Pbarbosa92 commented on inductiva/_cli/cmd_tasks/_tail.py
> +                           help="Number of lines to show.")
```suggestion
    subparser.add_argument("--lines",
                           "-l",
                           type=int,
                           default=10,
                           help="Number of lines to show.")
```

2024-12-18 09:16 UTC, Pbarbosa92 commented on inductiva/tasks/task.py
> +    async def _tail_file(self, filename: str, lines: int) -> str:
```suggestion
    async def _tail_file(self, filename: str, n_lines: int = 10) -> str:
```

2024-12-18 09:16 UTC, Pbarbosa92 commented on inductiva/tasks/task.py
>          """Get the last 10 lines of a file in the task's working directory."""
```suggestion
        """Get the last n_lines lines of a file in the task's working directory."""
```

2024-12-18 09:16 UTC, Pbarbosa92 commented on inductiva/tasks/task.py
> +                                          lines=lines)
```suggestion
                                          lines=n_lines)
```

2024-12-18 09:25 UTC, Pbarbosa92 requested changes
While trying to test this i was getting `File not found: flow_cylinder.xml,1` but the file flow_cylinder.xml is there present in the list files.

2024-12-18 09:29 UTC, rodrigotuna commented
> While trying to test this i was getting `File not found: flow_cylinder.xml,1` but the file flow_cylinder.xml is there present in the list files.

Can you send me which simulation you were using?

2024-12-18 09:52 UTC, Pbarbosa92 commented
> > While trying to test this i was getting `File not found: flow_cylinder.xml,1` but the file flow_cylinder.xml is there present in the list files.
> 
> Can you send me which simulation you were using?

```python
"""DualSPHysics example."""
import inductiva

# Instantiate machine group
machine_group = inductiva.resources.MachineGroup("c2-standard-4")
machine_group.start()

# Download the configuration files into a folder
input_dir = inductiva.utils.download_from_url(
    "https://storage.googleapis.com/inductiva-api-demo-files/"
    "dualsphysics-input-example.zip",
    unzip=True)

commands = [
    "gencase config flow_cylinder -save:all",
    "dualsphysics flow_cylinder flow_cylinder -dirdataout data -svres",
    ("partvtk -dirin flow_cylinder/data -savevtk flow_cylinder/PartFluid "
     "-onlytype:-all,+fluid")
]

# Initialize the Simulator
dualsphysics = inductiva.simulators.DualSPHysics()

# Run simulation with config files in the input directory
task = dualsphysics.run(input_dir=input_dir,
                        commands=commands,
                        on=machine_group)

task.wait()
task.download_outputs()

machine_group.terminate()
```

2024-12-18 14:20 UTC, rodrigotuna commented
> > > While trying to test this i was getting `File not found: flow_cylinder.xml,1` but the file flow_cylinder.xml is there present in the list files.
> > 
> > 
> > Can you send me which simulation you were using?
> 
> ```python
> """DualSPHysics example."""
> import inductiva
> 
> # Instantiate machine group
> machine_group = inductiva.resources.MachineGroup("c2-standard-4")
> machine_group.start()
> 
> # Download the configuration files into a folder
> input_dir = inductiva.utils.download_from_url(
>     "https://storage.googleapis.com/inductiva-api-demo-files/"
>     "dualsphysics-input-example.zip",
>     unzip=True)
> 
> commands = [
>     "gencase config flow_cylinder -save:all",
>     "dualsphysics flow_cylinder flow_cylinder -dirdataout data -svres",
>     ("partvtk -dirin flow_cylinder/data -savevtk flow_cylinder/PartFluid "
>      "-onlytype:-all,+fluid")
> ]
> 
> # Initialize the Simulator
> dualsphysics = inductiva.simulators.DualSPHysics()
> 
> # Run simulation with config files in the input directory
> task = dualsphysics.run(input_dir=input_dir,
>                         commands=commands,
>                         on=machine_group)
> 
> task.wait()
> task.download_outputs()
> 
> machine_group.terminate()
> ```

The problem is that the current task-runner image in use in dev is not expecting the number of lines parameter, that is why the filename has the `,1`  suffix (the number of lines). 
You can test the by running the task-runner locally from the branch in [this PR](https://github.com/inductiva/task-runner/pull/86) and it should work.

2025-01-02 14:44 UTC, rodrigotuna commented
> > The problem is that the current task-runner image in use in dev is not expecting the number of lines parameter, that is why the filename has the `,1` suffix (the number of lines). You can test again by running the task-runner locally from the branch in [this PR](https://github.com/inductiva/task-runner/pull/86) and it should work.
> 
> Could we have issues if, for some reason, there's a file that includes `,` in the name? Maybe we could have a more robust way of encoding the args (such as `json`, or something like that).

Will be solved in a subsequent PR

2025-01-03 16:35 UTC, Pbarbosa92 approved these changes

2025-01-03 16:37 UTC, merged