486-code-examples-in-tutorials-should-show-the-full-range-of-parameter-options
inductiva/inductiva pull request #1773
Opened 2024-12-19 09:35 UTC by Pbarbosa92

This PR adds more arguments to the examples.

2024-12-19 09:35 UTC, Pbarbosa92 commented
@sarmento can you let me know if this arguments that I've added are enough?

2024-12-19 12:02 UTC, sarmento requested changes
´´´
from datetime import timedelta

# Instantiate machine group
machine_group = inductiva.resources.MachineGroup(
    "c2-standard-4", spot=True, max_idle_time=timedelta(minutes=1))

´´´

We need to remove the need to import a module for saying you don't want the machine idle for more than one minute.

2024-12-19 12:29 UTC, Pbarbosa92 commented on examples/amr_wind/amr_wind.py
> +amr_wind = inductiva.simulators.AmrWind(version="1.4.0")
I would rather have all examples uniform and not some with version some without version.

2025-01-06 09:40 UTC, Pbarbosa92 commented on examples/amr_wind/amr_wind.py
> +    "c2-standard-4", spot=True, max_idle_time=timedelta(minutes=1))
@hpenedones can you comment on this? I'm ok with allowing the max idle time to be only in minutes and changing the parameter to `max_idle_time_minutes` (int) and converting to time delta on the method.

2025-01-06 15:54 UTC, hpenedones commented on examples/amr_wind/amr_wind.py
> +    "c2-standard-4", spot=True, max_idle_time=timedelta(minutes=1))
Yes, let's try to avoid imports to just construct arguments to pass to our methods.
```max_idle_time_minutes``` could work... but we might need indeed to introduce it as a new argument, and deprecate the other one later (start showing a print saying it's deprecated and to use the new argument instead).

2025-01-06 15:58 UTC, hpenedones commented on examples/amr_wind/amr_wind.py
> +    "c2-standard-4", spot=True, max_idle_time=timedelta(minutes=1))
or otherwise, we would need to accept ```max_idle_time``` taking different types (either you pass a timedelta and you can have arbitrary precision there) or if you pass an integer it would be treated as minutes and we create the timedelta inside. 
Typically I don't like this kind of "optional" things -- with different types -- but here the alternative is to nearly duplicate that argument (with a name that is longer, with the suffix "minutes") and deal with the deprecation process... which is also not super neat...

2025-01-06 16:46 UTC, Pbarbosa92 commented on examples/amr_wind/amr_wind.py
> +    "c2-standard-4", spot=True, max_idle_time=timedelta(minutes=1))
I'll create a new issue to do this small change.

2025-02-27 11:01 UTC, hpenedones commented
is this pull request active @Pbarbosa92 : or should we close it?

2025-02-27 11:12 UTC, Pbarbosa92 commented
> is this pull request active @Pbarbosa92 : or should we close it?

We can close it. We are already taking this approach as we update all tutorials we have.

2025-02-27 11:12 UTC, closed without merging